version: '3.9'
services:
    tracker:
        image: file-club-tracker
        container_name: tracker
        build: .
        command: ["go", "run", "cmd/tracker/main.go", "assets/test_file.txt"]
    bigTracker:
        image: big-club-tracker
        container_name: bigTracker
        build: .
        command: ["go", "run", "cmd/bigFile/main.go"]
    tests:
        image: test-club-tracker
        container_name: tracker-tests
        build: .
        command: ["go", "test", "-v", "github.com/Fedosdekudrille/club-tracker/internal/data", "github.com/Fedosdekudrille/club-tracker/internal/club"]